name: protractor-es6modules-typescript-jasmine

on: 
  push:
  schedule:
    - cron: '0 0 1-31/2 * *' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: INSTALL, BUILD
      run: |
        npm ci
        npm run lint
        npm run build
      env:
        CI: true
    - name: npm install, build, and test
      run: |
        npm run upadte-webderiver
        npm run test-ci
